[tool.black]
line-length = 88
target-version = ['py39']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3
include_trailing_comma = true
known_third_party = ["PySide6", "numpy", "pandas"]
known_local_folder = ["gui", "database", "utils"]

[tool.pylint.messages_control]
disable = "C0111"

[tool.pylint.format]
max-line-length = "88"

[tool.mypy]
python_version = 3.9
ignore_missing_imports = true
strict = true

[mypy]
python_version = "3.8"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = false
disallow_incomplete_defs = false
