cookie:
  expiry_days: 30
  key: gonetwork_auth
  name: gonetwork_auth
credentials:
  usernames:
    admin:
      email: admin@gonetwork.com
      name: Administrador
      password: $2b$12$6a2uUWuOOufskwpU3CCmU..t2vIPAaRokCRUdyXcLabO8eQ2yRIfu
